# Chapter 2

In [1]:
import torch
import numpy as np
import pandas as pd

**1. Create a tensor `a` from `list(range(9))` . Predict then check what the size, offset, and strides are.**

In [2]:
a = torch.tensor(list(range(9)))

Predict:

- size: [9]
  
- offset: 0

- strides: (1)

Check:

In [3]:
print(a)
print("size:", a.size())
print("offset:", a.storage_offset())
print("strides:", a.stride())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
size: torch.Size([9])
offset: 0
strides: (1,)


**2. Create a tensor `b = a.view(3, 3)` . What is the value of `b[1, 1]` ?**

In [4]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

value of `b[1, 1]` :

In [5]:
b[1, 1]

tensor(4)

**3. Create a tensor `c = b[1:,1:]` . Predict then check what the size, offset, and strides are.**

In [6]:
c = b[1:,1:]

Predict:

- size: [2, 2]

- offset: 4

- strides: (3, 1)

Check:

In [7]:
print(c)
print("size:", c.size())
print("offset:", c.storage_offset())
print("strides:", c.stride())

tensor([[4, 5],
        [7, 8]])
size: torch.Size([2, 2])
offset: 4
strides: (3, 1)
